netif-naming-scheme: disable NAMING_BRIDGE_MULTIFUNCTION_SLOT
redhat-plumbers/systemd-rhel9 pull request #283
Opened 2024-07-01 13:36 UTC by lnykryn

This effectively reverts 66425daf2c68793adf24a48a26d58add8662e83f.

The commit assumes that if the network interface has multifunctions, then the function fields of the pci devices under the same PCI bridge device are unique.
But it seems not, at least on some setups. See issue #28929. Let's revert the change, and always refuse to set slot base naming if a PCI bridge is detected.

Fixes #28929.

(cherry picked from commit af7417ac7b07bc01232982bf46e9d72e69e7f820)

Resolves: RHEL-44630

2024-07-02 08:39 UTC, msekletar requested changes
I don't like the wording of the manpage paragraph. It is difficult to understand in my opinion so I've tried to rewrite it for better clarity

```
Never generate a slot name when a PCI bridge is detected.

Since version "rhel-9.0", we have generated slot-based names for PCI multifunction devices, because we assumed that it is enough to use function numbers to distinguish between devices. However, name conflict can occur if these devices are not children of the same PCI bridge, e.g. there are multiple PCI bridges in the same slot.
```

2024-07-03 08:02 UTC, msekletar approved these changes
LGTM

2024-07-03 08:13 UTC, merged

2024-07-03 14:53 UTC, champtar commented
You are missing `{ "rhel-9.5", NAMING_RHEL_9_5 }` in the .c

2024-07-03 15:00 UTC, lnykryn commented
> You are missing `{ "rhel-9.5", NAMING_RHEL_9_5 }` in the .c

Good catch thanks! https://github.com/redhat-plumbers/systemd-rhel9/pull/284