Don't GC unit if it is in another queue
redhat-plumbers/systemd-rhel9 pull request #299
Opened 2024-09-10 11:33 UTC by dtardon

Resolves: RHEL-55301

2025-01-13 14:33 UTC, msekletar requested changes
I think that github action warning is a real issue which should be fixed.

2025-01-13 14:58 UTC, jamacku commented
> I think that github action warning is a real issue which should be fixed.

We need https://github.com/systemd/systemd/commit/cb153b4fe9046590eb8efba66b67a0db899cb96d or we have to use the original name `test/units/assert.sh`.

https://github.com/systemd/systemd/commits/cb153b4fe9046590eb8efba66b67a0db899cb96d/test/units/assert.sh?browsing_rename_history=true&new_path=test/units/util.sh&original_branch=main

2025-01-17 07:08 UTC, dtardon commented
> > I think that github action warning is a real issue which should be fixed.
> 
> We need [systemd/systemd@cb153b4](https://github.com/systemd/systemd/commit/cb153b4fe9046590eb8efba66b67a0db899cb96d) or we have to use the original name `test/units/assert.sh`.
> 
> https://github.com/systemd/systemd/commits/cb153b4fe9046590eb8efba66b67a0db899cb96d/test/units/assert.sh?browsing_rename_history=true&new_path=test/units/util.sh&original_branch=main

I backported the rename.

2025-01-17 09:28 UTC, jamacku commented
CI failure is unrelated

```
Failed to write PK secure boot variable: Security violation
systemd-stub@0x67d7b000,0x67d93000
Overlapping PE sections detected. Boot may fail due to image memory corruption!
```

2025-01-27 15:27 UTC, msekletar approved these changes
LGTM

2025-01-27 16:15 UTC, merged