Return ESRCH if userdb service refuses a user/group name as invalid
redhat-plumbers/systemd-rhel9 pull request #302
Opened 2024-10-24 13:16 UTC by dtardon

Resolves: RHEL-55266

2024-10-25 11:11 UTC, jamacku commented
@dtardon I have noticed that this PR references two issues. Could you please split it into two PRs? Thank you.

2024-10-29 07:38 UTC, dtardon commented
> @dtardon I have noticed that this PR references two issues. Could you please split it into two PRs? Thank you.

The references to RHEL-55301 are a mistake. Fixed.

2025-01-13 14:55 UTC, msekletar requested changes
As per CI results it seems that backport doesn't compile due to issues with json-util.h include. @dtardon can you please double check.

2025-01-17 06:58 UTC, dtardon commented
> As per CI results it seems that backport doesn't compile due to issues with json-util.h include. @dtardon can you please double check.

Oops, sorry. I fixed the include months ago, but then forgot to push...

2025-01-17 09:27 UTC, jamacku commented
CI failure is unrelated

```
Failed to write PK secure boot variable: Security violation
systemd-stub@0x67d7b000,0x67d93000
Overlapping PE sections detected. Boot may fail due to image memory corruption!
```

2025-01-27 15:26 UTC, msekletar approved these changes
LGTM

2025-01-27 15:48 UTC, merged